### ISSUE TITLE
Discord game detection not working

### ISSUE THREAD

**Issue by Maxwell-lt** [Maxwell-lt/TitleChanger#1]
Apparently Discord detects the file name, not the window title. I doubt this can be fixed except on Discord's end.

**Comment by adrwa** [comment]
People can change what their games are called in the discord client itself, as an example 
![image](https://cloud.githubusercontent.com/assets/17037059/22410320/94f8cb94-e68e-11e6-9803-4936b21ccc87.png)

What im really "playing" is notepad++

**Comment by Maxwell-lt** [comment]
Well, I guess this really isn't needed then.
