### ISSUE TITLE
Update to 1.12

### ISSUE THREAD

**Issue by ghost** [Maxwell-lt/TitleChanger#4]
Hello
Can you update this mod to 1.12?

**Comment by Maxwell-lt** [comment]
I will work on updating this mod when I get some free time.

It shouldn't be too difficult to finish the update, I can't imagine it taking more than a few days.

**Comment by Ghostlyr** [comment]
Current sources are fully compatible with new versions except for a few strings.
https://github.com/Ghostlyr/TitleChanger/blob/master/releases/titlechanger-1.1.2.jar
