### ISSUE TITLE
Mod Crashes Server

### ISSUE THREAD

**Issue by adwalters** [Maxwell-lt/TitleChanger#6]
When installed onto a forge server, it crashes the server. Most client-sided mods do not do this.

Error:
> [19:31:18] [Server thread/ERROR] [FML]: An error occurred trying to load a proxy into maxwell_lt.titlechanger.TitleChanger.proxy
> java.lang.ClassNotFoundException: maxwell_lt.titlechanger.TitleChanger$ServerProxy

**Comment by Maxwell-lt** [comment]
Try using version 1.1.4, I believe the issue has been fixed.
