### ISSUE TITLE
How can I change the Title in the config

### ISSUE THREAD

**Issue by Titoo8899** [Maxwell-lt/TitleChanger#7]
hi,
I will a new name in the Title adding. Not more Minecraft 1.12.2. I will the Name: WatchCity add.

This is your config. Can you say me what I must change to add a new title in Minecraft?

# Configuration file

##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# General configuration
##########################################################################################################

general {
    # Format to display time in. See http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns [default: h:mm a]
    S:timeformat=h:mm a

    # The title of the Minecraft window. Leave blank to keep the default window title for your version of Minecraft.
    # Some special values that will be inserted at runtime:
    # %mcver% -> The current Minecraft version
    # %modcount% -> Number of loaded mods
    # %time% -> Current system time
    #  [default: ]
    S:windowtitle=
}

**Comment by Maxwell-lt** [comment]
If you want the title to be "Watch City", then the config file should look like this:

```
# Configuration file

##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# General configuration
##########################################################################################################

general {
    # Format to display time in. See http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns [default: h:mm a]
    S:timeformat=h:mm a

    # The title of the Minecraft window. Leave blank to keep the default window title for your version of Minecraft.
    # Some special values that will be inserted at runtime:
    # %mcver% -> The current Minecraft version
    # %modcount% -> Number of loaded mods
    # %time% -> Current system time
    #  [default: ]
    S:windowtitle=Watch City
}
```
