### ISSUE TITLE
Mod TitleChanger was a Memory fail

### ISSUE THREAD

**Issue by Titoo8899** [Maxwell-lt/TitleChanger#8]
hi,
your mod work and is good but the Memory was to high then I load your mod. Please make a performance Update

**Comment by Maxwell-lt** [comment]
This mod should have a trivial impact on performance and resource usage. Are you sure that the memory usage is significantly higher when this mod is installed?

Also, please describe the issue in more detail, and attach a full list of the mods you have installed. If the game crashed, please attach a full crash log.
